"""
Master Build 06 — AI Sales Agent Action Policy, State Models & Risk Tiers
========================================================================
Canonical definitions for:
  1. AgentState & CustomerJourneyState
  2. ActionRiskTier (LOW, MEDIUM, HIGH, CRITICAL)
  3. NextBestActionType & AutonomyLevel
  4. ProposedActionDTO
  5. ActionPolicyEngine (Deterministic enterprise policy & autonomy gates)

NON-NEGOTIABLE INVARIANTS:
  - LLMs NEVER decide policy or permissions.
  - Critical actions (booking, payments, cancellations) CANNOT be autonomous.
  - Every proposed action carries risk tier, evidence, confidence, and authorization rules.
"""
from __future__ import annotations

import enum
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Set, Tuple


# ─── 1. State Models (Sections 7 & 8) ────────────────────────────────────────

class AgentState(str, enum.Enum):
    """
    Deterministic conversation agent state machine states.
    Controls the current conversational objective.
    """
    NEW = "NEW"
    UNDERSTANDING = "UNDERSTANDING"
    QUALIFYING = "QUALIFYING"
    DISCOVERING = "DISCOVERING"
    RECOMMENDING = "RECOMMENDING"
    ANSWERING = "ANSWERING"
    OBJECTION_HANDLING = "OBJECTION_HANDLING"
    FOLLOW_UP = "FOLLOW_UP"
    WAITING = "WAITING"
    HANDOFF_REQUIRED = "HANDOFF_REQUIRED"
    HUMAN_ACTIVE = "HUMAN_ACTIVE"
    RESOLVED = "RESOLVED"


class CustomerJourneyState(str, enum.Enum):
    """
    Customer business lifecycle state, tracked separately from raw conversation turns.
    Derived from structured evidence (qualification facts, viewings, offers).
    """
    NEW_LEAD = "NEW_LEAD"
    CONTACTED = "CONTACTED"
    QUALIFYING = "QUALIFYING"
    QUALIFIED = "QUALIFIED"
    PROPERTY_DISCOVERY = "PROPERTY_DISCOVERY"
    PROPERTY_SHORTLIST = "PROPERTY_SHORTLIST"
    ENGAGED = "ENGAGED"
    APPOINTMENT_PROPOSED = "APPOINTMENT_PROPOSED"
    APPOINTMENT_CONFIRMED = "APPOINTMENT_CONFIRMED"
    SITE_VISIT_SCHEDULED = "SITE_VISIT_SCHEDULED"
    SITE_VISIT_COMPLETED = "SITE_VISIT_COMPLETED"
    NEGOTIATION = "NEGOTIATION"
    BOOKING_READY = "BOOKING_READY"
    BOOKED = "BOOKED"
    LOST = "LOST"
    NURTURING = "NURTURING"


# ─── 2. Action Risk Tiers & Action Types (Sections 28, 31, 32) ────────────────

class ActionRiskTier(str, enum.Enum):
    """
    Action risk classification determining authorization requirements.
    """
    LOW = "LOW"            # Read property, search knowledge, summarize, analyze
    MEDIUM = "MEDIUM"      # Draft response, propose question, suggest alternatives
    HIGH = "HIGH"          # Send outbound message, schedule site visit, assign lead
    CRITICAL = "CRITICAL"  # Booking confirmation, reservation, payment, cancellation


class NextBestActionType(str, enum.Enum):
    """
    Canonical action types emitted by the NextBestActionEngine.
    """
    NO_ACTION = "NO_ACTION"
    ASK_QUALIFICATION = "ASK_QUALIFICATION"
    SEND_PROPERTY = "SEND_PROPERTY"
    ANSWER_QUESTION = "ANSWER_QUESTION"
    HANDLE_OBJECTION = "HANDLE_OBJECTION"
    FOLLOW_UP = "FOLLOW_UP"
    SCHEDULE_APPOINTMENT = "SCHEDULE_APPOINTMENT"
    CONFIRM_APPOINTMENT = "CONFIRM_APPOINTMENT"
    HANDOFF_HUMAN = "HANDOFF_HUMAN"
    WAIT = "WAIT"


class AutonomyLevel(str, enum.Enum):
    """
    Configurable autonomy levels per tenant / team / action type.
    """
    AUTO_EXECUTE = "AUTO_EXECUTE"         # AI executes safely without human intervention
    CONFIRM_REQUIRED = "CONFIRM_REQUIRED" # AI drafts/prepares; human or explicit auth confirms
    HUMAN_REQUIRED = "HUMAN_REQUIRED"     # Exclusively human broker action; AI hands off
    DISABLED = "DISABLED"                 # Action type is completely disallowed


# ─── 3. Proposed Action DTO ───────────────────────────────────────────────────

@dataclass
class ProposedActionDTO:
    """
    Structured action proposal generated by the agent / NBA engine.
    Contains complete audit trail, evidence, confidence, and authorization state.
    """
    action_type: NextBestActionType
    risk_tier: ActionRiskTier
    reason: str
    evidence: Dict[str, Any] = field(default_factory=dict)
    confidence: float = 0.8
    urgency: str = "medium"               # low | medium | high | critical
    expected_outcome: str = ""
    parameters: Dict[str, Any] = field(default_factory=dict)
    requires_authorization: bool = False
    authorization_id: Optional[str] = None
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def to_dict(self) -> Dict[str, Any]:
        return {
            "action_type": self.action_type.value,
            "risk_tier": self.risk_tier.value,
            "reason": self.reason,
            "evidence": self.evidence,
            "confidence": self.confidence,
            "urgency": self.urgency,
            "expected_outcome": self.expected_outcome,
            "parameters": self.parameters,
            "requires_authorization": self.requires_authorization,
            "authorization_id": self.authorization_id,
            "created_at": self.created_at.isoformat(),
        }


# ─── 4. Action Policy Engine ──────────────────────────────────────────────────

class ActionPolicyEngine:
    """
    Evaluates enterprise governance, tenant autonomy configurations,
    and action safety rules before execution.
    """

    # Default baseline autonomy map:
    # LOW risk: AUTO_EXECUTE
    # MEDIUM risk: AUTO_EXECUTE or CONFIRM_REQUIRED
    # HIGH risk: CONFIRM_REQUIRED
    # CRITICAL risk: HUMAN_REQUIRED / strict authorization
    DEFAULT_POLICY: Dict[NextBestActionType, Tuple[ActionRiskTier, AutonomyLevel]] = {
        NextBestActionType.NO_ACTION: (ActionRiskTier.LOW, AutonomyLevel.AUTO_EXECUTE),
        NextBestActionType.WAIT: (ActionRiskTier.LOW, AutonomyLevel.AUTO_EXECUTE),
        NextBestActionType.ANSWER_QUESTION: (ActionRiskTier.LOW, AutonomyLevel.AUTO_EXECUTE),
        NextBestActionType.ASK_QUALIFICATION: (ActionRiskTier.MEDIUM, AutonomyLevel.AUTO_EXECUTE),
        NextBestActionType.SEND_PROPERTY: (ActionRiskTier.MEDIUM, AutonomyLevel.AUTO_EXECUTE),
        NextBestActionType.HANDLE_OBJECTION: (ActionRiskTier.MEDIUM, AutonomyLevel.AUTO_EXECUTE),
        NextBestActionType.FOLLOW_UP: (ActionRiskTier.HIGH, AutonomyLevel.CONFIRM_REQUIRED),
        NextBestActionType.SCHEDULE_APPOINTMENT: (ActionRiskTier.HIGH, AutonomyLevel.CONFIRM_REQUIRED),
        NextBestActionType.CONFIRM_APPOINTMENT: (ActionRiskTier.CRITICAL, AutonomyLevel.CONFIRM_REQUIRED),
        NextBestActionType.HANDOFF_HUMAN: (ActionRiskTier.LOW, AutonomyLevel.AUTO_EXECUTE),
    }

    def __init__(self, tenant_policies: Optional[Dict[str, Dict[str, str]]] = None):
        self._tenant_policies = tenant_policies or {}

    def get_risk_tier(self, action_type: NextBestActionType) -> ActionRiskTier:
        entry = self.DEFAULT_POLICY.get(action_type)
        return entry[0] if entry else ActionRiskTier.HIGH

    def get_action_risk_tier(self, action_type: NextBestActionType) -> ActionRiskTier:
        return self.get_risk_tier(action_type)

    def configure_action_policy(
        self,
        organization_id: str,
        action_type: NextBestActionType,
        autonomy_level: AutonomyLevel,
    ) -> None:
        org_key = str(organization_id)
        if org_key not in self._tenant_policies:
            self._tenant_policies[org_key] = {}
        self._tenant_policies[org_key][action_type.value] = autonomy_level.value

    def get_autonomy_level(
        self,
        organization_id: str,
        action_type: NextBestActionType,
        risk_tier: Optional[ActionRiskTier] = None,
        is_human_active: bool = False,
        is_paused: bool = False,
    ) -> AutonomyLevel:
        autonomy, _, _ = self.evaluate_autonomy(
            organization_id=organization_id,
            action_type=action_type,
            is_human_active=is_human_active,
            is_paused=is_paused,
        )
        return autonomy

    def requires_authorization(
        self,
        organization_id: str,
        action_type: NextBestActionType,
        risk_tier: Optional[ActionRiskTier] = None,
        is_human_active: bool = False,
        is_paused: bool = False,
    ) -> bool:
        _, req_auth, _ = self.evaluate_autonomy(
            organization_id=organization_id,
            action_type=action_type,
            is_human_active=is_human_active,
            is_paused=is_paused,
        )
        return req_auth

    def evaluate_autonomy(
        self,
        organization_id: str,
        action_type: NextBestActionType,
        is_human_active: bool = False,
        is_paused: bool = False,
    ) -> Tuple[AutonomyLevel, bool, str]:
        """
        Evaluates whether an action can be executed autonomously, requires confirmation,
        or is blocked.
        Returns: (AutonomyLevel, requires_authorization, reason)
        """
        # Rule 1: If human takeover is active, all autonomous outreach is blocked
        if is_human_active:
            return (
                AutonomyLevel.HUMAN_REQUIRED,
                True,
                "Human takeover is active for this conversation. Autonomous execution blocked.",
            )

        # Rule 2: If emergency pause is active, execution is blocked
        if is_paused:
            return (
                AutonomyLevel.DISABLED,
                True,
                "Emergency automation pause is active. Outbound execution suppressed.",
            )

        # Rule 3: Check tenant-specific override
        org_overrides = self._tenant_policies.get(str(organization_id), {})
        override = org_overrides.get(action_type.value)
        if override:
            try:
                autonomy = AutonomyLevel(override)
            except ValueError:
                autonomy = self.DEFAULT_POLICY.get(action_type, (ActionRiskTier.HIGH, AutonomyLevel.CONFIRM_REQUIRED))[1]
        else:
            autonomy = self.DEFAULT_POLICY.get(action_type, (ActionRiskTier.HIGH, AutonomyLevel.CONFIRM_REQUIRED))[1]

        # Rule 4: Critical actions ALWAYS require authorization regardless of config
        risk_tier = self.get_risk_tier(action_type)
        if risk_tier == ActionRiskTier.CRITICAL:
            requires_auth = True
            if autonomy == AutonomyLevel.AUTO_EXECUTE:
                autonomy = AutonomyLevel.CONFIRM_REQUIRED
        elif autonomy in (AutonomyLevel.CONFIRM_REQUIRED, AutonomyLevel.HUMAN_REQUIRED):
            requires_auth = True
        else:
            requires_auth = False

        reason = (
            f"Action {action_type.value} evaluated at risk tier {risk_tier.value} "
            f"with autonomy level {autonomy.value}."
        )
        return autonomy, requires_auth, reason
