"""
Part 21.7 — AI Conversation & Customer Response Intelligence Taxonomies
========================================================================
Controlled enumerations and classifications for:
- Customer Intents
- Buying Signal Levels & Indicators
- Objection Categories & Severities
- Negotiation Signals
- Appointment Intent Types
- Response Strategy & Handoff Triggers
"""
from enum import Enum


class CustomerIntent(str, Enum):
    """Classified customer intent categories."""
    BUYING_INTENT = "BUYING_INTENT"
    SELLING_INTENT = "SELLING_INTENT"
    RENTING_INTENT = "RENTING_INTENT"
    INVESTING_INTENT = "INVESTING_INTENT"
    INFORMATION_REQUEST = "INFORMATION_REQUEST"
    PROPERTY_REQUEST = "PROPERTY_REQUEST"
    PRICE_OBJECTION = "PRICE_OBJECTION"
    BUDGET_CHANGE = "BUDGET_CHANGE"
    LOCATION_CHANGE = "LOCATION_CHANGE"
    PROPERTY_TYPE_CHANGE = "PROPERTY_TYPE_CHANGE"
    BEDROOM_CHANGE = "BEDROOM_CHANGE"
    TIMELINE_CHANGE = "TIMELINE_CHANGE"
    FINANCING_DISCUSSION = "FINANCING_DISCUSSION"
    VIEWING_REQUEST = "VIEWING_REQUEST"
    VIEWING_CONFIRMATION = "VIEWING_CONFIRMATION"
    VIEWING_RESCHEDULE = "VIEWING_RESCHEDULE"
    VIEWING_CANCELLATION = "VIEWING_CANCELLATION"
    NEGOTIATION = "NEGOTIATION"
    POSITIVE_INTEREST = "POSITIVE_INTEREST"
    NEGATIVE_INTEREST = "NEGATIVE_INTEREST"
    NEUTRAL = "NEUTRAL"
    COMPLAINT = "COMPLAINT"
    LEGAL_RISK = "LEGAL_RISK"
    OPT_OUT = "OPT_OUT"
    STOP_COMMUNICATION = "STOP_COMMUNICATION"
    HUMAN_AGENT_REQUEST = "HUMAN_AGENT_REQUEST"
    UNCLEAR = "UNCLEAR"


class BuyingSignalLevel(str, Enum):
    """Calibrated buying signal confidence levels."""
    VERY_HIGH = "VERY_HIGH"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    NONE = "NONE"
    UNKNOWN = "UNKNOWN"


class BuyingSignalIndicator(str, Enum):
    """Specific evidence-grounded buying signal indicators."""
    VIEWING_REQUEST = "VIEWING_REQUEST"
    PAYMENT_DETAILS_REQUEST = "PAYMENT_DETAILS_REQUEST"
    AVAILABILITY_INQUIRY = "AVAILABILITY_INQUIRY"
    NEGOTIATION_INQUIRY = "NEGOTIATION_INQUIRY"
    DOCUMENTATION_REQUEST = "DOCUMENTATION_REQUEST"
    MORTGAGE_INQUIRY = "MORTGAGE_INQUIRY"
    POSSESSION_INQUIRY = "POSSESSION_INQUIRY"
    BOOKING_INQUIRY = "BOOKING_INQUIRY"
    SIMILAR_PROPERTIES_REQUEST = "SIMILAR_PROPERTIES_REQUEST"
    EXPLICIT_TIMEFRAME = "EXPLICIT_TIMEFRAME"
    EXPLICIT_WILLINGNESS = "EXPLICIT_WILLINGNESS"


class ObjectionCategory(str, Enum):
    """Structured customer objection classifications."""
    PRICE = "PRICE"
    LOCATION = "LOCATION"
    PROPERTY_SIZE = "PROPERTY_SIZE"
    PROPERTY_TYPE = "PROPERTY_TYPE"
    AMENITIES = "AMENITIES"
    PAYMENT_TERMS = "PAYMENT_TERMS"
    FINANCING = "FINANCING"
    TIMELINE = "TIMELINE"
    TRUST = "TRUST"
    DOCUMENTATION = "DOCUMENTATION"
    AVAILABILITY = "AVAILABILITY"
    POSSESSION = "POSSESSION"
    INVESTMENT_RETURN = "INVESTMENT_RETURN"
    OTHER = "OTHER"


class ObjectionSeverity(str, Enum):
    """Severity of customer objection."""
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class AppointmentIntentType(str, Enum):
    """Viewing & meeting intent classifications."""
    REQUEST = "REQUEST"
    CONFIRMATION = "CONFIRMATION"
    RESCHEDULE = "RESCHEDULE"
    CANCELLATION = "CANCELLATION"
    AVAILABILITY_QUERY = "AVAILABILITY_QUERY"
    NONE = "NONE"


class NegotiationDirection(str, Enum):
    """Direction of pricing negotiation."""
    DISCOUNT_REQUEST = "DISCOUNT_REQUEST"
    COUNTER_OFFER = "COUNTER_OFFER"
    PAYMENT_PLAN_REQUEST = "PAYMENT_PLAN_REQUEST"
    WAIVER_REQUEST = "WAIVER_REQUEST"
    NONE = "NONE"


class HandoffTrigger(str, Enum):
    """Triggers requiring human intervention."""
    CUSTOMER_REQUEST = "CUSTOMER_REQUEST"
    COMPLAINT = "COMPLAINT"
    LEGAL_RISK = "LEGAL_RISK"
    AGGRESSIVE_NEGOTIATION = "AGGRESSIVE_NEGOTIATION"
    HIGH_VALUE_TRANSACTION = "HIGH_VALUE_TRANSACTION"
    QUALIFICATION_CONFLICT = "QUALIFICATION_CONFLICT"
    CONTRACT_DOCUMENT_REQUEST = "CONTRACT_DOCUMENT_REQUEST"
    UNCERTAIN_INTERPRETATION = "UNCERTAIN_INTERPRETATION"
    CUSTOMER_DISSATISFACTION = "CUSTOMER_DISSATISFACTION"
    NONE = "NONE"
